language: python
python:
  - "2.7"
install: pip install -r requirements.txt
before_script:
  - pip install coverage
  - pip install python-coveralls
  - pip install pep8
  - cp travis-ci/manage.py manage.py
  - python manage.py syncdb --noinput
script:
  - pep8 scraper/ --exclude=migrations,scraper/test
  - coverage run --source=scraper/ manage.py test scraper
after_script:
  - coveralls
